import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Feed from '../components/Feed'
import NavBar from '../components/NavBar'
import SideBar from '../components/SideBar'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className='bg-black'>
      <Head>
        <title>Gamocracy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* 
        2nd: #121212
        Red: #DC143C hover: #e5163f
      */}

      <NavBar />
      <main className='min-h-screen flex max-w-full mx-auto xl:mx-32'>
          <div className='w-2/12 hidden md:flex pt-2 md:mt-12 md:mr-4 lg:mr-0'>
            <SideBar />
          </div>
          <div className='w-full md:w-7/12 mt-2'>
            <Feed />
          </div>
          <div className='w-3/12 hidden md:flex pt-2 md:mt-12 border border-gray-800 ml-2'>
            <SideBar />
          </div>
      </main>
    </div>
  )
}

export default Home
